  version: '2.6.1'

  services:
    couchbase:
      container_name: couchbase
      image: couchbase:6.6.6
      ports:
        - '8091:8091'
        - '8092:8092'
        - '8093:8093'
        - '8094:8094'
        - '11210:11210'

    todoservice:
      image: todo-service
      container_name: todo-service-app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always

